require 'spec_helper'

feature 'CRUD pots' do

  scenario 'User can create a list of pots' do
    visit '/'
    expect(page).to have_content 'Welcome'
    click_on 'Add a pot'
    fill_in 'Size', with: 'Large'
    fill_in 'Color', with: 'Orange'
    fill_in 'Owner', with: 'Suzy'
    click_on 'Add pot'
    expect(page).to have_content 'Large'
    expect(page).to have_content 'Orange'
    expect(page).to have_content 'Suzy'
  end

  scenario 'User can update a pot from list' do
    visit '/'
    expect(page).to have_content 'Welcome'
    click_on 'Add a pot'
    fill_in 'Size', with: 'Large'
    fill_in 'Color', with: 'Orange'
    fill_in 'Owner', with: 'Suzy'
    click_on 'Add pot'
    expect(page).to have_content 'Large'
    expect(page).to have_content 'Orange'
    expect(page).to have_content 'Suzy'
    click_on 'Large'
    expect(page).to have_content 'Large'
    expect(page).to have_content 'Orange'
    expect(page).to have_content 'Suzy'
    click_on 'Edit'
    fill_in 'Size', with: 'Small'
    fill_in 'Color', with: 'Blue'
    fill_in 'Owner', with: 'John'
    click_on 'Update pot'
    expect(page).to have_content 'Small'
    expect(page).to have_content 'Blue'
    expect(page).to have_content 'John'
    expect(page).to_not have_content 'Large'
    expect(page).to_not have_content 'Orange'
    expect(page).to_not have_content 'Suzy'
  end

  scenario 'User can delete a pot from list' do
    visit '/'
    expect(page).to have_content 'Welcome'
    click_on 'Add a pot'
    fill_in 'Size', with: 'Large'
    fill_in 'Color', with: 'Orange'
    fill_in 'Owner', with: 'Suzy'
    click_on 'Add pot'
    expect(page).to have_content 'Large'
    expect(page).to have_content 'Orange'
    expect(page).to have_content 'Suzy'
    click_on 'Large'
    expect(page).to have_content 'Large'
    expect(page).to have_content 'Orange'
    expect(page).to have_content 'Suzy'
    click_on 'Delete'
    expect(page).to_not have_content 'Large'
    expect(page).to_not have_content 'Orange'
    expect(page).to_not have_content 'Suzy'
  end
end